<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTeamsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('teams', function (Blueprint $table) {
            $table->increments('id');
            $table->string('school_name');
            $table->string('short_name')->nullable();
            $table->string('conference')->nullable();
            $table->string('mascot')->nullable();
            $table->string('state')->nullable();
            $table->string('image_file')->nullable();
            $table->string('website')->nullable();
            $table->timestamps();
        });

        DB::statement("
            INSERT INTO ncaa.teams
                (school_name, short_name, conference, mascot, state, image_file, website, created_at, updated_at)
            VALUES
                ('Cincinnati' , '' , 'AAC' , 'Bearcats' , '' , '' , '' , now(), now()), 
                ('Connecticut' , '' , 'AAC' , 'Huskies' , '' , '' , '' , now(), now()), 
                ('East Carolina' , '' , 'AAC' , 'Pirates' , '' , '' , '' , now(), now()), 
                ('Houston' , '' , 'AAC' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('Memphis' , '' , 'AAC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('SMU' , '' , 'AAC' , 'Mustangs' , '' , '' , '' , now(), now()), 
                ('South Florida' , '' , 'AAC' , 'Bulls' , '' , '' , '' , now(), now()), 
                ('Temple' , '' , 'AAC' , 'Owls' , '' , '' , '' , now(), now()), 
                ('Tulane' , '' , 'AAC' , 'Green Wave' , '' , '' , '' , now(), now()), 
                ('Tulsa' , '' , 'AAC' , 'Golden Hurricane' , '' , '' , '' , now(), now()), 
                ('UCF' , '' , 'AAC' , 'Knights' , '' , '' , '' , now(), now()), 
                ('Boston College' , '' , 'ACC' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Clemson' , '' , 'ACC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Duke' , '' , 'ACC' , 'Blue Devils' , '' , '' , '' , now(), now()), 
                ('Florida State' , '' , 'ACC' , 'Seminoles' , '' , '' , '' , now(), now()), 
                ('Georgia Tech' , '' , 'ACC' , 'Yellow Jackets' , '' , '' , '' , now(), now()), 
                ('Louisville' , '' , 'ACC' , 'Cardinals' , '' , '' , '' , now(), now()), 
                ('Miami (FL)' , '' , 'ACC' , 'Hurricanes' , '' , '' , '' , now(), now()), 
                ('North Carolina' , '' , 'ACC' , 'Tar Heels' , '' , '' , '' , now(), now()), 
                ('North Carolina State' , '' , 'ACC' , 'Wolfpack' , '' , '' , '' , now(), now()), 
                ('Notre Dame' , '' , 'ACC' , 'Fighting Irish' , '' , '' , '' , now(), now()), 
                ('Pittsburgh' , '' , 'ACC' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Syracuse' , '' , 'ACC' , 'Orange' , '' , '' , '' , now(), now()), 
                ('Virginia' , '' , 'ACC' , 'Cavaliers' , '' , '' , '' , now(), now()), 
                ('Virginia Tech' , '' , 'ACC' , 'Hokies' , '' , '' , '' , now(), now()), 
                ('Wake Forest' , '' , 'ACC' , 'Demon Deacons' , '' , '' , '' , now(), now()), 
                ('Albany' , '' , 'American East' , 'Great Danes' , '' , '' , '' , now(), now()), 
                ('Binghamton' , '' , 'American East' , 'Bearcats' , '' , '' , '' , now(), now()), 
                ('Hartford' , '' , 'American East' , 'Hawks' , '' , '' , '' , now(), now()), 
                ('Maine' , '' , 'American East' , 'Black Bears' , '' , '' , '' , now(), now()), 
                ('Massachusetts-Lowell' , '' , 'American East' , 'River Hawks' , '' , '' , '' , now(), now()), 
                ('New Hampshire' , '' , 'American East' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Stony Brook' , '' , 'American East' , 'Seawolves' , '' , '' , '' , now(), now()), 
                ('UMBC' , '' , 'American East' , 'Retrievers' , '' , '' , '' , now(), now()), 
                ('Vermont' , '' , 'American East' , 'Catamounts' , '' , '' , '' , now(), now()), 
                ('Davidson' , '' , 'Atlantic 10' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Dayton' , '' , 'Atlantic 10' , 'Flyers' , '' , '' , '' , now(), now()), 
                ('Duquesne' , '' , 'Atlantic 10' , 'Dukes' , '' , '' , '' , now(), now()), 
                ('Fordham' , '' , 'Atlantic 10' , 'Rams' , '' , '' , '' , now(), now()), 
                ('George Mason' , '' , 'Atlantic 10' , 'Patriots' , '' , '' , '' , now(), now()), 
                ('George Washington' , '' , 'Atlantic 10' , 'Colonials' , '' , '' , '' , now(), now()), 
                ('La Salle' , '' , 'Atlantic 10' , 'Explorers' , '' , '' , '' , now(), now()), 
                ('Massachusetts' , '' , 'Atlantic 10' , 'Minutemen' , '' , '' , '' , now(), now()), 
                ('Rhode Island' , '' , 'Atlantic 10' , 'Rams' , '' , '' , '' , now(), now()), 
                ('Richmond' , '' , 'Atlantic 10' , 'Spiders' , '' , '' , '' , now(), now()), 
                ('Saint Joseph''s' , '' , 'Atlantic 10' , 'Hawks' , '' , '' , '' , now(), now()), 
                ('Saint Louis' , '' , 'Atlantic 10' , 'Billikens' , '' , '' , '' , now(), now()), 
                ('St. Bonaventure' , '' , 'Atlantic 10' , 'Bonnies' , '' , '' , '' , now(), now()), 
                ('VCU' , '' , 'Atlantic 10' , 'Rams' , '' , '' , '' , now(), now()), 
                ('FGCU' , '' , 'Atlantic Sun' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Jacksonville' , '' , 'Atlantic Sun' , 'Dolphins' , '' , '' , '' , now(), now()), 
                ('Kennesaw State' , '' , 'Atlantic Sun' , 'Owls' , '' , '' , '' , now(), now()), 
                ('Lipscomb' , '' , 'Atlantic Sun' , 'Bisons' , '' , '' , '' , now(), now()), 
                ('NJIT' , '' , 'Atlantic Sun' , 'Highlanders' , '' , '' , '' , now(), now()), 
                ('North Florida' , '' , 'Atlantic Sun' , 'Ospreys' , '' , '' , '' , now(), now()), 
                ('Stetson' , '' , 'Atlantic Sun' , 'Hatters' , '' , '' , '' , now(), now()), 
                ('USC Upstate' , '' , 'Atlantic Sun' , 'Spartans' , '' , '' , '' , now(), now()), 
                ('Baylor' , '' , 'Big 12' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Iowa State' , '' , 'Big 12' , 'Cyclones' , '' , '' , '' , now(), now()), 
                ('Kansas' , '' , 'Big 12' , 'Jayhawks' , '' , '' , '' , now(), now()), 
                ('Kansas State' , '' , 'Big 12' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Oklahoma' , '' , 'Big 12' , 'Sooners' , '' , '' , '' , now(), now()), 
                ('Oklahoma State' , '' , 'Big 12' , 'Cowboys' , '' , '' , '' , now(), now()), 
                ('TCU' , '' , 'Big 12' , 'Horned Frogs' , '' , '' , '' , now(), now()), 
                ('Texas' , '' , 'Big 12' , 'Longhorns' , '' , '' , '' , now(), now()), 
                ('Texas Tech' , '' , 'Big 12' , 'Red Raiders' , '' , '' , '' , now(), now()), 
                ('West Virginia' , '' , 'Big 12' , 'Mountaineers' , '' , '' , '' , now(), now()), 
                ('Butler' , '' , 'Big East' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Creighton' , '' , 'Big East' , 'Bluejays' , '' , '' , '' , now(), now()), 
                ('DePaul' , '' , 'Big East' , 'Blue Demons' , '' , '' , '' , now(), now()), 
                ('Georgetown' , '' , 'Big East' , 'Hoyas' , '' , '' , '' , now(), now()), 
                ('Marquette' , '' , 'Big East' , 'Golden Eagles' , '' , '' , '' , now(), now()), 
                ('Providence' , '' , 'Big East' , 'Friars' , '' , '' , '' , now(), now()), 
                ('Seton Hall' , '' , 'Big East' , 'Pirates' , '' , '' , '' , now(), now()), 
                ('St. John''s' , '' , 'Big East' , 'Red Storm' , '' , '' , '' , now(), now()), 
                ('Villanova' , '' , 'Big East' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Xavier' , '' , 'Big East' , 'Musketeers' , '' , '' , '' , now(), now()), 
                ('Eastern Washington' , '' , 'Big Sky' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Idaho' , '' , 'Big Sky' , 'Vandals' , '' , '' , '' , now(), now()), 
                ('Idaho State' , '' , 'Big Sky' , 'Bengals' , '' , '' , '' , now(), now()), 
                ('Montana' , '' , 'Big Sky' , 'Grizzlies' , '' , '' , '' , now(), now()), 
                ('Montana State' , '' , 'Big Sky' , 'Bobcats' , '' , '' , '' , now(), now()), 
                ('North Dakota' , '' , 'Big Sky' , 'Fighting Hawks' , '' , '' , '' , now(), now()), 
                ('Northern Arizona' , '' , 'Big Sky' , 'Lumberjacks' , '' , '' , '' , now(), now()), 
                ('Northern Colorado' , '' , 'Big Sky' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Portland State' , '' , 'Big Sky' , 'Vikings' , '' , '' , '' , now(), now()), 
                ('Sacramento State' , '' , 'Big Sky' , 'Hornets' , '' , '' , '' , now(), now()), 
                ('Southern Utah' , '' , 'Big Sky' , 'Thunderbirds' , '' , '' , '' , now(), now()), 
                ('Weber State' , '' , 'Big Sky' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Campbell' , '' , 'Big South' , 'Fighting Camels' , '' , '' , '' , now(), now()), 
                ('Charleston Southern' , '' , 'Big South' , 'Buccaneers' , '' , '' , '' , now(), now()), 
                ('Coastal Carolina' , '' , 'Big South' , 'Chanticleers' , '' , '' , '' , now(), now()), 
                ('Gardner-Webb' , '' , 'Big South' , 'Runnin'' Bulldogs' , '' , '' , '' , now(), now()), 
                ('High Point' , '' , 'Big South' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Liberty' , '' , 'Big South' , 'Flames' , '' , '' , '' , now(), now()), 
                ('Longwood' , '' , 'Big South' , 'Lancers' , '' , '' , '' , now(), now()), 
                ('Presbyterian' , '' , 'Big South' , 'Blue Hose' , '' , '' , '' , now(), now()), 
                ('Radford' , '' , 'Big South' , 'Highlanders' , '' , '' , '' , now(), now()), 
                ('UNC Asheville' , '' , 'Big South' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Winthrop' , '' , 'Big South' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Illinois' , '' , 'Big Ten' , 'Fighting Illini' , '' , '' , '' , now(), now()), 
                ('Indiana' , '' , 'Big Ten' , 'Hoosiers' , '' , '' , '' , now(), now()), 
                ('Iowa' , '' , 'Big Ten' , 'Hawkeyes' , '' , '' , '' , now(), now()), 
                ('Maryland' , '' , 'Big Ten' , 'Terrapins' , '' , '' , '' , now(), now()), 
                ('Michigan' , '' , 'Big Ten' , 'Wolverines' , '' , '' , '' , now(), now()), 
                ('Michigan State' , '' , 'Big Ten' , 'Spartans' , '' , '' , '' , now(), now()), 
                ('Minnesota' , '' , 'Big Ten' , 'Golden Gophers' , '' , '' , '' , now(), now()), 
                ('Nebraska' , '' , 'Big Ten' , 'Cornhuskers' , '' , '' , '' , now(), now()), 
                ('Northwestern' , '' , 'Big Ten' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Ohio State' , '' , 'Big Ten' , 'Buckeyes' , '' , '' , '' , now(), now()), 
                ('Penn State' , '' , 'Big Ten' , 'Nittany Lions' , '' , '' , '' , now(), now()), 
                ('Purdue' , '' , 'Big Ten' , 'Boilermakers' , '' , '' , '' , now(), now()), 
                ('Rutgers' , '' , 'Big Ten' , 'Scarlet Knights' , '' , '' , '' , now(), now()), 
                ('Wisconsin' , '' , 'Big Ten' , 'Badgers' , '' , '' , '' , now(), now()), 
                ('Cal Poly' , '' , 'Big West' , 'Mustangs' , '' , '' , '' , now(), now()), 
                ('Cal State Fullerton' , '' , 'Big West' , 'Titans' , '' , '' , '' , now(), now()), 
                ('CSUN' , '' , 'Big West' , 'Matadors' , '' , '' , '' , now(), now()), 
                ('Hawaii' , '' , 'Big West' , 'Rainbow Warriors' , '' , '' , '' , now(), now()), 
                ('Long Beach State' , '' , 'Big West' , '49Ers' , '' , '' , '' , now(), now()), 
                ('UC Davis' , '' , 'Big West' , 'Aggies' , '' , '' , '' , now(), now()), 
                ('UC Irvine' , '' , 'Big West' , 'Anteaters' , '' , '' , '' , now(), now()), 
                ('UC Riverside' , '' , 'Big West' , 'Highlanders' , '' , '' , '' , now(), now()), 
                ('UC Santa Barbara' , '' , 'Big West' , 'Gauchos' , '' , '' , '' , now(), now()), 
                ('Charleston' , '' , 'CAA' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('Delaware' , '' , 'CAA' , 'Fightin'' Blue Hens' , '' , '' , '' , now(), now()), 
                ('Drexel' , '' , 'CAA' , 'Dragons' , '' , '' , '' , now(), now()), 
                ('Elon' , '' , 'CAA' , 'Phoenix' , '' , '' , '' , now(), now()), 
                ('Hofstra' , '' , 'CAA' , 'Pride' , '' , '' , '' , now(), now()), 
                ('James Madison' , '' , 'CAA' , 'Dukes' , '' , '' , '' , now(), now()), 
                ('Northeastern' , '' , 'CAA' , 'Huskies' , '' , '' , '' , now(), now()), 
                ('Towson' , '' , 'CAA' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('UNCW' , '' , 'CAA' , 'Seahawks' , '' , '' , '' , now(), now()), 
                ('William & Mary' , '' , 'CAA' , 'Tribe' , '' , '' , '' , now(), now()), 
                ('Charlotte' , '' , 'Conference Usa' , '49Ers' , '' , '' , '' , now(), now()), 
                ('FIU' , '' , 'Conference Usa' , 'Golden Panthers' , '' , '' , '' , now(), now()), 
                ('Florida Atlantic' , '' , 'Conference Usa' , 'Owls' , '' , '' , '' , now(), now()), 
                ('Louisiana Tech' , '' , 'Conference Usa' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Marshall' , '' , 'Conference Usa' , 'Thundering Herd' , '' , '' , '' , now(), now()), 
                ('Middle Tennessee' , '' , 'Conference Usa' , 'Blue Raiders' , '' , '' , '' , now(), now()), 
                ('North Texas' , '' , 'Conference Usa' , 'Mean Green' , '' , '' , '' , now(), now()), 
                ('Old Dominion' , '' , 'Conference Usa' , 'Monarchs' , '' , '' , '' , now(), now()), 
                ('Rice' , '' , 'Conference Usa' , 'Owls' , '' , '' , '' , now(), now()), 
                ('Southern Miss' , '' , 'Conference Usa' , 'Golden Eagles' , '' , '' , '' , now(), now()), 
                ('UAB' , '' , 'Conference Usa' , 'Blazers' , '' , '' , '' , now(), now()), 
                ('UTEP' , '' , 'Conference Usa' , 'Miners' , '' , '' , '' , now(), now()), 
                ('UTSA' , '' , 'Conference Usa' , 'Roadrunners' , '' , '' , '' , now(), now()), 
                ('Western Kentucky' , '' , 'Conference Usa' , 'Hilltoppers' , '' , '' , '' , now(), now()), 
                ('Cleveland State' , '' , 'Horizon' , 'Vikings' , '' , '' , '' , now(), now()), 
                ('Detroit' , '' , 'Horizon' , 'Titans' , '' , '' , '' , now(), now()), 
                ('Green Bay' , '' , 'Horizon' , 'Phoenix' , '' , '' , '' , now(), now()), 
                ('Milwaukee' , '' , 'Horizon' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Northern Kentucky' , '' , 'Horizon' , 'Norse' , '' , '' , '' , now(), now()), 
                ('Oakland' , '' , 'Horizon' , 'Golden Grizzlies' , '' , '' , '' , now(), now()), 
                ('UIC' , '' , 'Horizon' , 'Flames' , '' , '' , '' , now(), now()), 
                ('Valparaiso' , '' , 'Horizon' , 'Crusaders' , '' , '' , '' , now(), now()), 
                ('Wright State' , '' , 'Horizon' , 'Raiders' , '' , '' , '' , now(), now()), 
                ('Youngstown State' , '' , 'Horizon' , 'Penguins' , '' , '' , '' , now(), now()), 
                ('Brown' , '' , 'Ivy' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Columbia' , '' , 'Ivy' , 'Lions' , '' , '' , '' , now(), now()), 
                ('Cornell' , '' , 'Ivy' , 'Big Red' , '' , '' , '' , now(), now()), 
                ('Dartmouth' , '' , 'Ivy' , 'Big Green' , '' , '' , '' , now(), now()), 
                ('Harvard' , '' , 'Ivy' , 'Crimson' , '' , '' , '' , now(), now()), 
                ('Penn' , '' , 'Ivy' , 'Quakers' , '' , '' , '' , now(), now()), 
                ('Princeton' , '' , 'Ivy' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Yale' , '' , 'Ivy' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Canisius' , '' , 'MAAC' , 'Golden Griffins' , '' , '' , '' , now(), now()), 
                ('Fairfield' , '' , 'MAAC' , 'Stags' , '' , '' , '' , now(), now()), 
                ('Iona' , '' , 'MAAC' , 'Gaels' , '' , '' , '' , now(), now()), 
                ('Manhattan' , '' , 'MAAC' , 'Jaspers' , '' , '' , '' , now(), now()), 
                ('Marist' , '' , 'MAAC' , 'Red Foxes' , '' , '' , '' , now(), now()), 
                ('Monmouth' , '' , 'MAAC' , 'Hawks' , '' , '' , '' , now(), now()), 
                ('Niagara' , '' , 'MAAC' , 'Purple Eagles' , '' , '' , '' , now(), now()), 
                ('Quinnipiac' , '' , 'MAAC' , 'Bobcats' , '' , '' , '' , now(), now()), 
                ('Rider' , '' , 'MAAC' , 'Broncs' , '' , '' , '' , now(), now()), 
                ('Saint Peter''s' , '' , 'MAAC' , 'Peacocks' , '' , '' , '' , now(), now()), 
                ('Siena' , '' , 'MAAC' , 'Saints' , '' , '' , '' , now(), now()), 
                ('Akron' , '' , 'MAC' , 'Zips' , '' , '' , '' , now(), now()), 
                ('Ball State' , '' , 'MAC' , 'Cardinals' , '' , '' , '' , now(), now()), 
                ('Bowling Green' , '' , 'MAC' , 'Falcons' , '' , '' , '' , now(), now()), 
                ('Buffalo' , '' , 'MAC' , 'Bulls' , '' , '' , '' , now(), now()), 
                ('Central Michigan' , '' , 'MAC' , 'Chippewas' , '' , '' , '' , now(), now()), 
                ('Eastern Michigan' , '' , 'MAC' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Kent State' , '' , 'MAC' , 'Golden Flashes' , '' , '' , '' , now(), now()), 
                ('Miami (OH)' , '' , 'MAC' , 'Redhawks' , '' , '' , '' , now(), now()), 
                ('Northern Illinois' , '' , 'MAC' , 'Huskies' , '' , '' , '' , now(), now()), 
                ('Ohio' , '' , 'MAC' , 'Bobcats' , '' , '' , '' , now(), now()), 
                ('Toledo' , '' , 'MAC' , 'Rockets' , '' , '' , '' , now(), now()), 
                ('Western Michigan' , '' , 'MAC' , 'Broncos' , '' , '' , '' , now(), now()), 
                ('Bethune-Cookman' , '' , 'MEAC' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Coppin State' , '' , 'MEAC' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Delaware State' , '' , 'MEAC' , 'Hornets' , '' , '' , '' , now(), now()), 
                ('Florida A&M' , '' , 'MEAC' , 'Rattlers' , '' , '' , '' , now(), now()), 
                ('Hampton' , '' , 'MEAC' , 'Pirates' , '' , '' , '' , now(), now()), 
                ('Howard' , '' , 'MEAC' , 'Bison' , '' , '' , '' , now(), now()), 
                ('Maryland Eastern Shore' , '' , 'MEAC' , 'Hawks' , '' , '' , '' , now(), now()), 
                ('Morgan State' , '' , 'MEAC' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Norfolk State' , '' , 'MEAC' , 'Spartans' , '' , '' , '' , now(), now()), 
                ('North Carolina A&T' , '' , 'MEAC' , 'Aggies' , '' , '' , '' , now(), now()), 
                ('North Carolina Central' , '' , 'MEAC' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Savannah State' , '' , 'MEAC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('South Carolina State' , '' , 'MEAC' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Bradley' , '' , 'Missouri Valley' , 'Braves' , '' , '' , '' , now(), now()), 
                ('Drake' , '' , 'Missouri Valley' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Evansville' , '' , 'Missouri Valley' , 'Aces' , '' , '' , '' , now(), now()), 
                ('Illinois State' , '' , 'Missouri Valley' , 'Redbirds' , '' , '' , '' , now(), now()), 
                ('Indiana State' , '' , 'Missouri Valley' , 'Sycamores' , '' , '' , '' , now(), now()), 
                ('Loyola Chicago' , '' , 'Missouri Valley' , 'Ramblers' , '' , '' , '' , now(), now()), 
                ('Missouri State' , '' , 'Missouri Valley' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Southern Illinois' , '' , 'Missouri Valley' , 'Salukis' , '' , '' , '' , now(), now()), 
                ('UNI' , '' , 'Missouri Valley' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Wichita State' , '' , 'Missouri Valley' , 'Shockers' , '' , '' , '' , now(), now()), 
                ('Air Force' , '' , 'Mountain West' , 'Falcons' , '' , '' , '' , now(), now()), 
                ('Boise State' , '' , 'Mountain West' , 'Broncos' , '' , '' , '' , now(), now()), 
                ('Colorado State' , '' , 'Mountain West' , 'Rams' , '' , '' , '' , now(), now()), 
                ('Fresno State' , '' , 'Mountain West' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Nevada' , '' , 'Mountain West' , 'Wolf Pack' , '' , '' , '' , now(), now()), 
                ('New Mexico' , '' , 'Mountain West' , 'Lobos' , '' , '' , '' , now(), now()), 
                ('San Diego State' , '' , 'Mountain West' , 'Aztecs' , '' , '' , '' , now(), now()), 
                ('San Jose State' , '' , 'Mountain West' , 'Spartans' , '' , '' , '' , now(), now()), 
                ('UNLV' , '' , 'Mountain West' , 'Runnin'' Rebels' , '' , '' , '' , now(), now()), 
                ('Utah State' , '' , 'Mountain West' , 'Aggies' , '' , '' , '' , now(), now()), 
                ('Wyoming' , '' , 'Mountain West' , 'Cowboys' , '' , '' , '' , now(), now()), 
                ('Bryant' , '' , 'Northeast' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Central Connecticut State' , '' , 'Northeast' , 'Blue Devils' , '' , '' , '' , now(), now()), 
                ('Fairleigh Dickinson' , '' , 'Northeast' , 'Knights' , '' , '' , '' , now(), now()), 
                ('LIU Brooklyn' , '' , 'Northeast' , 'Blackbirds' , '' , '' , '' , now(), now()), 
                ('Mount St. Mary''s' , '' , 'Northeast' , 'Mountaineers' , '' , '' , '' , now(), now()), 
                ('Robert Morris' , '' , 'Northeast' , 'Colonials' , '' , '' , '' , now(), now()), 
                ('Sacred Heart' , '' , 'Northeast' , 'Pioneers' , '' , '' , '' , now(), now()), 
                ('Saint Francis U' , '' , 'Northeast' , 'Red Flash' , '' , '' , '' , now(), now()), 
                ('St. Francis Brooklyn' , '' , 'Northeast' , 'Terriers' , '' , '' , '' , now(), now()), 
                ('Wagner' , '' , 'Northeast' , 'Seahawks' , '' , '' , '' , now(), now()), 
                ('Austin Peay' , '' , 'Ohio Valley' , 'Governors' , '' , '' , '' , now(), now()), 
                ('Belmont' , '' , 'Ohio Valley' , 'Bruins' , '' , '' , '' , now(), now()), 
                ('Eastern Illinois' , '' , 'Ohio Valley' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Eastern Kentucky' , '' , 'Ohio Valley' , 'Colonels' , '' , '' , '' , now(), now()), 
                ('Jacksonville State' , '' , 'Ohio Valley' , 'Gamecocks' , '' , '' , '' , now(), now()), 
                ('Morehead State' , '' , 'Ohio Valley' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Murray State' , '' , 'Ohio Valley' , 'Racers' , '' , '' , '' , now(), now()), 
                ('SIUE' , '' , 'Ohio Valley' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('Southeast Missouri State' , '' , 'Ohio Valley' , 'Redhawks' , '' , '' , '' , now(), now()), 
                ('Tennessee State' , '' , 'Ohio Valley' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Tennessee Tech' , '' , 'Ohio Valley' , 'Golden Eagles' , '' , '' , '' , now(), now()), 
                ('UT Martin' , '' , 'Ohio Valley' , 'Skyhawks' , '' , '' , '' , now(), now()), 
                ('Arizona' , '' , 'PAC-12' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Arizona State' , '' , 'PAC-12' , 'Sun Devils' , '' , '' , '' , now(), now()), 
                ('California' , '' , 'PAC-12' , 'Golden Bears' , '' , '' , '' , now(), now()), 
                ('Colorado' , '' , 'PAC-12' , 'Buffaloes' , '' , '' , '' , now(), now()), 
                ('Oregon' , '' , 'PAC-12' , 'Ducks' , '' , '' , '' , now(), now()), 
                ('Oregon State' , '' , 'PAC-12' , 'Beavers' , '' , '' , '' , now(), now()), 
                ('Stanford' , '' , 'PAC-12' , 'Cardinal' , '' , '' , '' , now(), now()), 
                ('UCLA' , '' , 'PAC-12' , 'Bruins' , '' , '' , '' , now(), now()), 
                ('USC' , '' , 'PAC-12' , 'Trojans' , '' , '' , '' , now(), now()), 
                ('Utah' , '' , 'PAC-12' , 'Runnin'' Utes' , '' , '' , '' , now(), now()), 
                ('Washington' , '' , 'PAC-12' , 'Huskies' , '' , '' , '' , now(), now()), 
                ('Washington State' , '' , 'PAC-12' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('American University' , '' , 'Patriot League' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Army West Point' , '' , 'Patriot League' , 'Black Knights' , '' , '' , '' , now(), now()), 
                ('Boston University' , '' , 'Patriot League' , 'Terriers' , '' , '' , '' , now(), now()), 
                ('Bucknell' , '' , 'Patriot League' , 'Bison' , '' , '' , '' , now(), now()), 
                ('Colgate' , '' , 'Patriot League' , 'Raiders' , '' , '' , '' , now(), now()), 
                ('Holy Cross' , '' , 'Patriot League' , 'Crusaders' , '' , '' , '' , now(), now()), 
                ('Lafayette' , '' , 'Patriot League' , 'Leopards' , '' , '' , '' , now(), now()), 
                ('Lehigh' , '' , 'Patriot League' , 'Mountain Hawks' , '' , '' , '' , now(), now()), 
                ('Loyola Maryland' , '' , 'Patriot League' , 'Greyhounds' , '' , '' , '' , now(), now()), 
                ('Navy' , '' , 'Patriot League' , 'Midshipmen' , '' , '' , '' , now(), now()), 
                ('Alabama' , '' , 'SEC' , 'Crimson Tide' , '' , '' , '' , now(), now()), 
                ('Arkansas' , '' , 'SEC' , 'Razorbacks' , '' , '' , '' , now(), now()), 
                ('Auburn' , '' , 'SEC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Florida' , '' , 'SEC' , 'Gators' , '' , '' , '' , now(), now()), 
                ('Georgia' , '' , 'SEC' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Kentucky' , '' , 'SEC' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('LSU' , '' , 'SEC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Mississippi State' , '' , 'SEC' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Missouri' , '' , 'SEC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Ole Miss' , '' , 'SEC' , 'Rebels' , '' , '' , '' , now(), now()), 
                ('South Carolina' , '' , 'SEC' , 'Gamecocks' , '' , '' , '' , now(), now()), 
                ('Tennessee' , '' , 'SEC' , 'Volunteers' , '' , '' , '' , now(), now()), 
                ('Texas A&M' , '' , 'SEC' , 'Aggies' , '' , '' , '' , now(), now()), 
                ('Vanderbilt' , '' , 'SEC' , 'Commodores' , '' , '' , '' , now(), now()), 
                ('Chattanooga' , '' , 'Southern' , 'Mocs' , '' , '' , '' , now(), now()), 
                ('Citadel' , '' , 'Southern' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('East Tennessee State' , '' , 'Southern' , 'Buccaneers' , '' , '' , '' , now(), now()), 
                ('Furman' , '' , 'Southern' , 'Paladins' , '' , '' , '' , now(), now()), 
                ('Mercer' , '' , 'Southern' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Samford' , '' , 'Southern' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('UNCG' , '' , 'Southern' , 'Spartans' , '' , '' , '' , now(), now()), 
                ('VMI' , '' , 'Southern' , 'Keydets' , '' , '' , '' , now(), now()), 
                ('Western Carolina' , '' , 'Southern' , 'Catamounts' , '' , '' , '' , now(), now()), 
                ('Wofford' , '' , 'Southern' , 'Terriers' , '' , '' , '' , now(), now()), 
                ('Abilene Christian' , '' , 'Southland' , 'Wildcats' , '' , '' , '' , now(), now()), 
                ('Central Arkansas' , '' , 'Southland' , 'Bears' , '' , '' , '' , now(), now()), 
                ('Houston Baptist' , '' , 'Southland' , 'Huskies' , '' , '' , '' , now(), now()), 
                ('Incarnate Word' , '' , 'Southland' , 'Cardinals' , '' , '' , '' , now(), now()), 
                ('Lamar' , '' , 'Southland' , 'Cardinals' , '' , '' , '' , now(), now()), 
                ('McNeese State' , '' , 'Southland' , 'Cowboys' , '' , '' , '' , now(), now()), 
                ('New Orleans' , '' , 'Southland' , 'Privateers' , '' , '' , '' , now(), now()), 
                ('Nicholls' , '' , 'Southland' , 'Colonels' , '' , '' , '' , now(), now()), 
                ('Northwestern State' , '' , 'Southland' , 'Demons' , '' , '' , '' , now(), now()), 
                ('Sam Houston State' , '' , 'Southland' , 'Bearkats' , '' , '' , '' , now(), now()), 
                ('Southeastern Louisiana' , '' , 'Southland' , 'Lions' , '' , '' , '' , now(), now()), 
                ('Stephen F. Austin' , '' , 'Southland' , 'Lumberjacks' , '' , '' , '' , now(), now()), 
                ('Texas A&M-Corpus Christi' , '' , 'Southland' , 'Islanders' , '' , '' , '' , now(), now()), 
                ('Denver' , '' , 'Summit League' , 'Pioneers' , '' , '' , '' , now(), now()), 
                ('IPFW' , '' , 'Summit League' , 'Mastodons' , '' , '' , '' , now(), now()), 
                ('IUPUI' , '' , 'Summit League' , 'Jaguars' , '' , '' , '' , now(), now()), 
                ('North Dakota State' , '' , 'Summit League' , 'Bison' , '' , '' , '' , now(), now()), 
                ('Omaha' , '' , 'Summit League' , 'Mavericks' , '' , '' , '' , now(), now()), 
                ('Oral Roberts' , '' , 'Summit League' , 'Golden Eagles' , '' , '' , '' , now(), now()), 
                ('South Dakota' , '' , 'Summit League' , 'Coyotes' , '' , '' , '' , now(), now()), 
                ('South Dakota State' , '' , 'Summit League' , 'Jackrabbits' , '' , '' , '' , now(), now()), 
                ('Western Illinois' , '' , 'Summit League' , 'Leathernecks' , '' , '' , '' , now(), now()), 
                ('Appalachian State' , '' , 'Sun Belt' , 'Mountaineers' , '' , '' , '' , now(), now()), 
                ('Arkansas State' , '' , 'Sun Belt' , 'Red Wolves' , '' , '' , '' , now(), now()), 
                ('Georgia Southern' , '' , 'Sun Belt' , 'Eagles' , '' , '' , '' , now(), now()), 
                ('Georgia State' , '' , 'Sun Belt' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Little Rock' , '' , 'Sun Belt' , 'Trojans' , '' , '' , '' , now(), now()), 
                ('Louisiana-Lafayette' , '' , 'Sun Belt' , 'Ragin'' Cajuns' , '' , '' , '' , now(), now()), 
                ('Louisiana-Monroe' , '' , 'Sun Belt' , 'Warhawks' , '' , '' , '' , now(), now()), 
                ('South Alabama' , '' , 'Sun Belt' , 'Jaguars' , '' , '' , '' , now(), now()), 
                ('Texas State' , '' , 'Sun Belt' , 'Bobcats' , '' , '' , '' , now(), now()), 
                ('Troy' , '' , 'Sun Belt' , 'Trojans' , '' , '' , '' , now(), now()), 
                ('UT Arlington' , '' , 'Sun Belt' , 'Mavericks' , '' , '' , '' , now(), now()), 
                ('Alabama A&M' , '' , 'SWAC' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Alabama State' , '' , 'SWAC' , 'Hornets' , '' , '' , '' , now(), now()), 
                ('Alcorn State' , '' , 'SWAC' , 'Braves' , '' , '' , '' , now(), now()), 
                ('Grambling State' , '' , 'SWAC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Jackson State' , '' , 'SWAC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Mississippi Valley State' , '' , 'SWAC' , 'Delta Devils' , '' , '' , '' , now(), now()), 
                ('Prairie View A&M' , '' , 'SWAC' , 'Panthers' , '' , '' , '' , now(), now()), 
                ('Southern University' , '' , 'SWAC' , 'Jaguars' , '' , '' , '' , now(), now()), 
                ('Texas Southern' , '' , 'SWAC' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('UAPB' , '' , 'SWAC' , 'Golden Lions' , '' , '' , '' , now(), now()), 
                ('Bakersfield' , '' , 'WAC' , 'Roadrunners' , '' , '' , '' , now(), now()), 
                ('Chicago State' , '' , 'WAC' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('Grand Canyon' , '' , 'WAC' , 'Antelopes' , '' , '' , '' , now(), now()), 
                ('New Mexico State' , '' , 'WAC' , 'Aggies' , '' , '' , '' , now(), now()), 
                ('Seattle' , '' , 'WAC' , 'Redhawks' , '' , '' , '' , now(), now()), 
                ('Texas-Rio Grande Valley' , '' , 'WAC' , 'Vaqueros' , '' , '' , '' , now(), now()), 
                ('UMKC' , '' , 'WAC' , 'Kangaroos' , '' , '' , '' , now(), now()), 
                ('Utah Valley' , '' , 'WAC' , 'Wolverines' , '' , '' , '' , now(), now()), 
                ('BYU' , '' , 'West Coast' , 'Cougars' , '' , '' , '' , now(), now()), 
                ('Gonzaga' , '' , 'West Coast' , 'Bulldogs' , '' , '' , '' , now(), now()), 
                ('Loyola Marymount' , '' , 'West Coast' , 'Lions' , '' , '' , '' , now(), now()), 
                ('Pacific' , '' , 'West Coast' , 'Tigers' , '' , '' , '' , now(), now()), 
                ('Pepperdine' , '' , 'West Coast' , 'Waves' , '' , '' , '' , now(), now()), 
                ('Portland' , '' , 'West Coast' , 'Pilots' , '' , '' , '' , now(), now()), 
                ('Saint Mary''s' , '' , 'West Coast' , 'Gaels' , '' , '' , '' , now(), now()), 
                ('San Diego' , '' , 'West Coast' , 'Toreros' , '' , '' , '' , now(), now()), 
                ('San Francisco' , '' , 'West Coast' , 'Dons' , '' , '' , '' , now(), now()), 
                ('Santa Clara' , '' , 'West Coast' , 'Broncos' , '' , '' , '' , now(), now())
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        Schema::dropIfExists('teams');
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
